defaults:
  - base

hydra:
  searchpath:
    - pkg://verl.trainer.config

trainer:
  experiment_name: frozenlake-main


es_manager:
  train:
    env_configs:
      tags: ["CoordFrozenLake"]
  val:
    env_configs:
      tags: ["CoordFrozenLake"]

custom_envs:
  CoordFrozenLake:
    env_config:
      success_rate: 0.02 # Probability of moving in the intended direction
      observation_format: "grid_coord"
