defaults:
  - base

micro_batch_size_per_gpu: 4
ppo_mini_batch_size: 32
model_path: Qwen/Qwen2.5-3B-Instruct

trainer:
  experiment_name: webshop_full


agent_proxy:
  max_turn: 15
  max_actions_per_turn: 1

actor_rollout_ref:
  rollout:
    max_model_len: 15000
    max_num_batched_tokens: 15000

es_manager:
  train:
    env_configs:
      tags: ["WebShopFull"]
  val:
    env_configs:
      tags: ["WebShopFull"]
